version: "3.9"
services:
    collector:
      build: collector
    server:
      build: server
    nginx:
      image: nginx
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8000:80"
    redis:
      image: redis
      volumes:
        - ./data:/data

